### ISSUE TITLE
WhatsApp Lite : Beta Testing 

### ISSUE THREAD

**Issue by raweee** [raweee/node-red-contrib-whatsapp-link#12]
Web sockets based whatsapp-lite is allmost finished, integrating the same in whatsapp-link node.
QR code and connections are completed.
Working on sending and receiving massages.

**Comment by ryangonzalez133** [comment]
after testing the lite version, it is no longer crashing, but when I connect to my whatsapp, the node appears as disconnected and does not change
![image](https://user-images.githubusercontent.com/109705835/214710995-49be5577-56c4-442d-8920-67f70bf23fdb.png)

**Comment by ryangonzalez133** [comment]
I've been doing some tests and I've verified that even though it appears as disconnected, I managed to receive the return of messages received for me, I haven't tested the rest of the functions yet. But for it to work, I had to follow the tutorial, I connected by the qr code and soon after it appeared as disconnected, so I just created another client and then it changed the status to "connected" without having to connect again by the qr code, I put the new client in the "chats" node in" node "admin" changed again to "disconnected" but I was able to receive the messages.

**Comment by raweee** [comment]
The status below the node, have to work on it.

But the node is always connected even if show disconnected, if it was disconnected it will show QR code.

**Comment by raweee** [comment]
After restart of node-red or machine, it should'nd asked for scanning of QR as the session is already store in 'whatsaap Link' folder.
Please that folder still remains or deleted when machin go down.
That folder 'whatsapp Link' is available in same folder where the settings.js and flow.json are located.

**Comment by ryangonzalez133** [comment]
hello friend, I could not find the folder or file named as "whatsapp link". The only folders and files I found were the "whatsapp web.js" folder and the "node-red-contrib-home-assistant-websocket" file as shown in the screenshot.

![Captura de Tela (10)](https://user-images.githubusercontent.com/109705835/214853913-5ae4a0d4-b2a5-429a-9bc5-e916f09f08aa.jpg)
![Captura de Tela (9)](https://user-images.githubusercontent.com/109705835/214853922-74042982-5232-4063-9f64-85acfacc2f86.jpg)

I don't understand what you mean by "After restart of node-red or machine, it should'nd asked for scanning of QR as the session is already store in 'whatsaap Link' folder." 
So every time i restart node-red or the machine i will have to go and connect with my whatsapp by the qr code? Wouldn't there be a way to store the session and always leave it saved?

**Comment by ryangonzalez133** [comment]
another folder I found was this one, but the name is not "whatsapp link" but "node-red-contrib-whatsapp-link" so I don't know if it's this one
![Captura de Tela (12)](https://user-images.githubusercontent.com/109705835/215079245-2c4562fe-7947-49ff-95bd-746745740e58.jpg)
![Captura de Tela (11)](https://user-images.githubusercontent.com/109705835/215079251-d4173989-916a-40e2-bac6-3b10384574e1.jpg)

**Comment by raweee** [comment]
Hi folder location sould be 

 `store your session locally in Node-RED. All data are store in users <user>/.node-red/Whatsapp-Link folder. Near you Node-Red's settings.js file.`

It might be hidden

**Comment by ryangonzalez133** [comment]
Would it be this? 
![image](https://user-images.githubusercontent.com/109705835/215088565-4ec4f5aa-2386-4f69-b088-b2c39be8eff9.png)

**Comment by raweee** [comment]
No, this is the correct folder. I'll make a option to choose the folder while publishing the node, in next release. 
So you can select your own folder to store sessions.

**Comment by ryangonzalez133** [comment]
I understand, what I told you is happening. To actually connect the node, after I scan the QR code, I have to create another client to connect, but after a while, it disconnects and I stop receiving the messages. Thanks for the work and development

**Comment by ryangonzalez133** [comment]
I have noticed that sometimes the node has crashed and I get this in the log.
I'm sending the log because I don't know if it helps you with something


"
Closing open session in favor of incoming prekey bundle
Closing session: SessionEntry {
  _chains: {
    'BUebzndgU/PbellEzwG1EvG9FXR7Kse0fk3h5pUn2Akq': { chainKey: [Object], chainType: 2, messageKeys: {} },
    'Bb4qpRcOKjeDbVfLiDU/AYHlBHdpQqBjrhtflpbHqaMB': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 156171663,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 be 2a a5 17 0e 2a 37 83 6d 57 cb 88 35 3f 01 81 e5 04 77 69 42 a0 63 ae 1b 5f 96 96 c7 a9 a3 01>,
      privKey: <Buffer 00 11 a4 5a 34 c9 ed 62 a0 f9 0f 4b 6b c6 2d 56 9d 32 59 3a a1 1c a3 69 cd 9f 0c b5 22 46 3b 4a>
    },
    lastRemoteEphemeralKey: <Buffer 05 47 9b ce 77 60 53 f3 db 7a 59 44 cf 01 b5 12 f1 bd 15 74 7b 2a c7 b4 7e 4d e1 e6 95 27 d8 09 2a>,
    previousCounter: 0,
    rootKey: <Buffer 32 aa de a4 1a 20 17 70 6d e6 26 b8 cb b3 d6 bd 78 39 94 2b 60 0f 8f 6e 34 32 5a 9f c8 b3 c4 d1>
  },
  indexInfo: {
    baseKey: <Buffer 05 b4 58 48 39 aa 0f 72 42 5e 74 27 8a bd e1 03 5a 81 72 0f b5 c9 d0 a6 ff 7c e0 2f cb 9e fd 6a 29>,
    baseKeyType: 2,
    closed: -1,
    used: 1674848003286,
    created: 1674848003286,
    remoteIdentityKey: <Buffer 05 81 16 48 e1 f1 7a 66 bc 60 a3 ff 95 f7 0a e1 6a 93 48 4c 99 97 64 7e 41 7e c6 43 b4 ee f5 b6 3d>
  }
}
Closing open session in favor of incoming prekey bundle
Closing session: SessionEntry {
  _chains: {
    'BUebzndgU/PbellEzwG1EvG9FXR7Kse0fk3h5pUn2Akq': { chainKey: [Object], chainType: 2, messageKeys: {} },
    'Bb4qpRcOKjeDbVfLiDU/AYHlBHdpQqBjrhtflpbHqaMB': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 156171663,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 be 2a a5 17 0e 2a 37 83 6d 57 cb 88 35 3f 01 81 e5 04 77 69 42 a0 63 ae 1b 5f 96 96 c7 a9 a3 01>,
      privKey: <Buffer 00 11 a4 5a 34 c9 ed 62 a0 f9 0f 4b 6b c6 2d 56 9d 32 59 3a a1 1c a3 69 cd 9f 0c b5 22 46 3b 4a>
    },
    lastRemoteEphemeralKey: <Buffer 05 47 9b ce 77 60 53 f3 db 7a 59 44 cf 01 b5 12 f1 bd 15 74 7b 2a c7 b4 7e 4d e1 e6 95 27 d8 09 2a>,
    previousCounter: 0,
    rootKey: <Buffer 32 aa de a4 1a 20 17 70 6d e6 26 b8 cb b3 d6 bd 78 39 94 2b 60 0f 8f 6e 34 32 5a 9f c8 b3 c4 d1>
  },
  indexInfo: {
    baseKey: <Buffer 05 b4 58 48 39 aa 0f 72 42 5e 74 27 8a bd e1 03 5a 81 72 0f b5 c9 d0 a6 ff 7c e0 2f cb 9e fd 6a 29>,
    baseKeyType: 2,
    closed: -1,
    used: 1674848003286,
    created: 1674848003286,
    remoteIdentityKey: <Buffer 05 81 16 48 e1 f1 7a 66 bc 60 a3 ff 95 f7 0a e1 6a 93 48 4c 99 97 64 7e 41 7e c6 43 b4 ee f5 b6 3d>
  }
}
27 Jan 16:33:28 - [info] Stopping modified flows
27 Jan 16:33:28 - [info] Stopped modified flows
27 Jan 16:33:28 - [info] Updated flows
27 Jan 16:33:28 - [info] Starting modified flows
27 Jan 16:33:28 - [info] Started modified flows
27 Jan 16:33:29 - [info] [chats-out:Chats Out] Error Sending Msg: Error: Connection Closed
{"level":40,"time":"2023-01-27T19:33:48.364Z","pid":294,"hostname":"a0d7b954-nodered","stack":"Error: mutex start\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n    at execTask (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n    at WebSocket.emit (node:events:513:28)\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1180:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:526:14)\n    at Receiver.getData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:459:17)\n    at Receiver.startLoop (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:158:22)\n    at Receiver._write (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:84:10)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Receiver.Writable.write (node:internal/streams/writable:337:10)\n    at TLSSocket.socketOnData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1274:35)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)","waitOver":true,"msg":"possible mutex deadlock"}
{"level":40,"time":"2023-01-27T19:33:48.377Z","pid":294,"hostname":"a0d7b954-nodered","stack":"Error: mutex start\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleNotification (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:422:29)\n    at execTask (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:569:9)\n    at WebSocket.emit (node:events:513:28)\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1180:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:526:14)\n    at Receiver.getData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:459:17)\n    at Receiver.startLoop (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:158:22)\n    at Receiver._write (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:84:10)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Receiver.Writable.write (node:internal/streams/writable:337:10)\n    at TLSSocket.socketOnData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1274:35)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)","waitOver":true,"msg":"possible mutex deadlock"}
{"level":40,"time":"2023-01-27T19:33:48.378Z","pid":294,"hostname":"a0d7b954-nodered","stack":"Error: mutex start\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n    at execTask (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n    at WebSocket.emit (node:events:513:28)\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1180:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:526:14)\n    at Receiver.getData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:459:17)\n    at Receiver.startLoop (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:158:22)\n    at Receiver._write (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:84:10)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Receiver.Writable.write (node:internal/streams/writable:337:10)\n    at TLSSocket.socketOnData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1274:35)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)","waitOver":true,"msg":"possible mutex deadlock"}
{"level":40,"time":"2023-01-27T19:33:48.379Z","pid":294,"hostname":"a0d7b954-nodered","stack":"Error: mutex start\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n    at execTask (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n    at WebSocket.emit (node:events:513:28)\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1180:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:526:14)\n    at Receiver.getData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:459:17)\n    at Receiver.startLoop (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:158:22)\n    at Receiver._write (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:84:10)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Receiver.Writable.write (node:internal/streams/writable:337:10)\n    at TLSSocket.socketOnData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1274:35)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)","waitOver":true,"msg":"possible mutex deadlock"}
{"level":40,"time":"2023-01-27T19:33:48.379Z","pid":294,"hostname":"a0d7b954-nodered","stack":"Error: mutex start\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n    at execTask (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n    at WebSocket.emit (node:events:513:28)\n    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1180:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:526:14)\n    at Receiver.getData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:459:17)\n    at Receiver.startLoop (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:158:22)\n    at Receiver._write (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/receiver.js:84:10)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Receiver.Writable.write (node:internal/streams/writable:337:10)\n    at TLSSocket.socketOnData (/config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/ws/lib/websocket.js:1274:35)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)","waitOver":true,"msg":"possible mutex deadlock"}
27 Jan 16:34:06 - [info] Stopping modified flows
27 Jan 16:34:06 - [info] Stopped modified flows
27 Jan 16:34:06 - [info] Updated flows
27 Jan 16:34:06 - [info] Starting modified flows
27 Jan 16:34:06 - [info] Started modified flows
Node Refressed
27 Jan 16:34:29 - [red] Uncaught Exception:
27 Jan 16:34:29 - [error] Error: Timed Out
    at /config/node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32
"

**Comment by paede81** [comment]
I have also the issue that it disconnect after a few hours. I tried to reconnect by sending restart to the admin node, but it seems that messages that I send to the admin node are ignore. The only way to reconnect is by open the config of the admin note, change to Whatsapp Web and back to lite do re-establish the connection for the next few hours. Btw the normal Whatsapp Web will never connect and status show connecting

**Comment by afcasasfranco** [comment]
HI

Great job, work very well.

Any change to use multiple accounts by websocket??

**Comment by raweee** [comment]
Hi @afcasasfranco ,
Multi user functionality was already in their.

**Comment by afcasasfranco** [comment]
@raweee perfect, but when try not give me another QR and on this moment the link disconnect in a couple of hours, do you know how can prevent the disconnect?

**Comment by raweee** [comment]
@afcasasfranco, 
yes I find that web sockets client goes in sleep after some time,
In next version I'll add a timer to ping or go online ever couple of hour(user defined time).

**Comment by raweee** [comment]
Hi @ryangonzalez133,
I find that it difficult to get a folder location by user in any browser. 
In search of any other option so user can also select a location for WhatsApp sessions.

**Comment by ryangonzalez133** [comment]
Hello friend, I gave up trying to use lite, it was giving an error all the time. So I installed node-red via docker separate from the Home assistant, at first it gave an error, so I installed puppeteer directly in the docker that worked fine doing this. 
Run the command: 

docker exec -it --user=root node-red /bin/sh

After entering your node-red docker file, a "node-red" folder will appear but at least for me, this is not the correct node-red folder, so you have to access where the node-red folder really is red, mine is in "/data/noderyan". So just "cd" to go back to the folders and find the right one, then run the following commands 

` 
apk update apk add --no-cache chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main

rm /data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome

ln -s /usr/bin/chromium-browser /data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome
 ` 
Use all commands with docker running.

So it worked fine, it doesn't ask to connect again with whatsapp and so far it hasn't given any errors, I'm using web, lite was giving an error all the time and when I restarted I had to connect again.

**Comment by ryangonzalez133** [comment]
hello friend @raweee , do you intend to put message compatibility by buttons in your node? It would be something very surprising

**Comment by jdntortosa** [comment]
> @afcasasfranco,
> yes I find that web sockets client goes in sleep after some time,
> In next version I'll add a timer to ping or go online ever couple of hour(user defined time).

Thks!! Great Job!! I'm waiting for it

**Comment by paede81** [comment]
@raweee any updates regarding WhatsApp lite and disconnects?

**Comment by raweee** [comment]
Whatsapp-Lite with Ping-Interval and Online/Offline mode added.

**Comment by paede81** [comment]
> Whatsapp-Lite with Ping-Interval and Online/Offline mode added.

Thanks a lot. One question: Why do I have to do a full restart of node-red when I just update you package? I don't have this behavior with other node red packages

**Comment by ryangonzalez133** [comment]
> > Whatsapp-Lite com Ping-Interval e modo Online/Offline adicionado.
> 
> Muito obrigado. Uma pergunta: Por que tenho que fazer uma reinicialização completa do node-red quando acabo de atualizar seu pacote? Eu não tenho esse comportamento com outros pacotes node red

I think this problem is happening only to you, because I just needed to restart to reconnect when the whatsapp connection drops

**Comment by paede81** [comment]
> Whatsapp-Lite with Ping-Interval and Online/Offline mode added.

It's not working. It's still disconnecting after a few hours, even if I set ping to 1 hour

**Comment by raweee** [comment]
Hi @paede81,
Now their are only 2 case it's show disconnected.
1. Case1 : logout (obvious reason to avoid connecting again and again).
2. Case2: lose/bad internet connection (if their was no internet at any time,it will remain disconnected) to avoid connecting again and again till nodered crashes.

You may check what is the exact reason of disconnection by selecting `connection.updates`  in chats-in node, which status of connection along with reason.

Let me know the reason of disconnection.
PS: Mine is working fine from last 23hrs.

**Comment by afcasasfranco** [comment]
> > Whatsapp-Lite with Ping-Interval and Online/Offline mode added.
> 
> 
> 
> It's not working. It's still disconnecting after a few hours, even if I set ping to 1 hour 

I'm test and work in the last 6 hours

**Comment by paede81** [comment]
> Hi @paede81, Now their are only 2 case it's show disconnected.
> 
> 1. Case1 : logout (obvious reason to avoid connecting again and again).
> 2. Case2: lose/bad internet connection (if their was no internet at any time,it will remain disconnected) to avoid connecting again and again till nodered crashes.
> 
> You may check what is the exact reason of disconnection by selecting `connection.updates` in chats-in node, which shows status of connection along with reason.
> 
> Let me know the reason of disconnection. PS: Mine is working fine from last 23hrs.

I will check.
One proposal: Instead of sending "Error Sending Msg:: Error: Connection Closed", can you trigger a reconnect if you try to send a message and connection is closed
