### ISSUE TITLE
Not receiving push messages

### ISSUE THREAD

**Issue by JapieG** [raweee/node-red-contrib-whatsapp-link#20]
Hi! First off all, thanks for your great work! 

When i activate this nodes i do not receive push messages anymore. Mayby i overlook it, but can i set the nodes session presence somewhere to unavailable? In that case whatsapp keeps sending push messages to my phone.

(by the way, i already saw a lot of other (minor) bugs. Do you want me to report them here? Or wait for some future releases first..)

**Comment by raweee** [comment]
Hi @JapieG,
You are not receiving push notifications because WhatsApp Bot is online all the time. In next update their would be a option to update the status in `whatsapp-link` node.

Reporting bugs here will help me to improve the Node. So minor-mazor bugs are always welcome.
Anything that helps to improve this node and learn the javascript.

**Comment by JapieG** [comment]
i see, thanks!!

Now looking into an issue why this nodes crash my nodered docker issues

**Comment by JapieG** [comment]
I tested 1.36, way better!

No crash anymore from my nodered while connecting, only a constant stream of errors in the debug log when not connected about an invalid whatsapp ping. But once is set the ping time and connected everything works fine. Great job!
