### ISSUE TITLE
Receiving works, sending doesn't

### ISSUE THREAD

**Issue by henkbb36org** [raweee/node-red-contrib-whatsapp-link#3]
Receiving messages works :-) But I when I send a message the server connection is lost and restored (a crash I guess, like the previous issue). No message is sent and I did use the correct phone number format... By the way, I am using a headless Linux server, when connecting the image viewer node to the whatsapp-admin node I see the QR code in NodeRed editor, that's nice.

**Comment by raweee** [comment]
No, Actually that was totally different from last issue, it was a minor mistake on mine :smile: , Due to which whatsappLink try to add two plus sign `++` in starting of number which causes lose in connection. 
Issue was fixed, from now (`Ver-0.1.16') we can use either of any one like :  `11 99999 99999` or `+11-9999999999` or `++11 99999 99999` or `Admin Number (11 99999 99999)' but international code is still required.
